/**
 * Power BI Schema Registry
 *
 * A static, AI-readable map of all Power BI tables, columns, and measures.
 * This replaces the need for discover_datasets + discover_schema API calls
 * on every conversation turn — the AI can look up the schema instantly.
 *
 * To update: modify this file, or run discover_schema when the Power BI
 * API is available and paste results here.
 */

export interface PbiColumn {
  name: string;
  type: "string" | "number" | "date" | "boolean";
  description?: string;
}

export interface PbiMeasure {
  name: string;
  description?: string;
}

export interface PbiTable {
  name: string;
  description: string;
  columns: PbiColumn[];
  measures: PbiMeasure[];
  /** Example DAX queries that work against this table */
  examples?: string[];
}

export interface PbiDataset {
  name: string;
  description: string;
  tables: Record<string, PbiTable>;
}

export interface PbiSchema {
  datasets: Record<string, PbiDataset>;
}

export const PBI_SCHEMA: PbiSchema = {
  datasets: {
    "prism-dashboards-prod": {
      name: "PRISM Dashboards PROD",
      description:
        "Primary production dataset containing utility KPI data across generation, distribution, reliability, financials, and operations. All tables use FY (fiscal year) and Utility as common dimensions.",
      tables: {
        "Fact GeneratorsData": {
          name: "Fact GeneratorsData",
          description:
            "Generator-level specifications: installed capacity, energy source, technology type, and operational status per utility per fiscal year.",
          columns: [
            { name: "Generator Name", type: "string", description: "Name of the generating unit" },
            { name: "Utility", type: "string", description: "Utility acronym (e.g., EPC, TPL)" },
            { name: "Utility ID", type: "number", description: "Utility identifier" },
            { name: "FY", type: "string", description: "Fiscal year (e.g., FY2022, FY2023)" },
            { name: "Installed Capacity (MW)", type: "number", description: "Nameplate capacity in megawatts" },
            { name: "Energy Source", type: "string", description: "Primary fuel/energy source (e.g., Diesel, Hydro, Solar)" },
            { name: "Energy Provider", type: "string", description: "Owner/operator of the generator" },
            { name: "Energy Type", type: "string", description: "Classification (e.g., Renewable, Non-Renewable)" },
            { name: "Service Area", type: "string", description: "Geographic service area" },
            { name: "GEN Electricity Generated", type: "number", description: "Actual electricity generated by this unit (MWh) — may be null" },
          ],
          measures: [
            { name: "Total Installed Capacity", description: "SUM of Installed Capacity (MW)" },
            { name: "Generator Count", description: "COUNT of Generator Name" },
          ],
          examples: [
            "EVALUATE SUMMARIZECOLUMNS('Fact GeneratorsData'[Utility], 'Fact GeneratorsData'[FY], \"Total MW\", SUM('Fact GeneratorsData'[Installed Capacity (MW)]))",
            "EVALUATE FILTER('Fact GeneratorsData', 'Fact GeneratorsData'[Energy Source] = \"Diesel\")",
          ],
        },
        "Fact Generation": {
          name: "Fact Generation",
          description:
            "Utility-level generation output, electricity demand (peak and average), and operational metrics per fiscal year.",
          columns: [
            { name: "Utility", type: "string", description: "Utility acronym" },
            { name: "FY", type: "string", description: "Fiscal year" },
            { name: "GEN Electricity Generated (MWh)", type: "number", description: "Total electricity generated (MWh) — utility-level aggregate" },
            { name: "Electricity Demand Peak Load", type: "number", description: "Peak electricity demand (MW)" },
            { name: "Electricity Demand Average Load", type: "number", description: "Average electricity demand (MW)" },
            { name: "Service Area", type: "string", description: "Geographic service area" },
            { name: "Energy Source", type: "string", description: "Generation source category" },
          ],
          measures: [
            { name: "Total Generation MWh", description: "SUM of GEN Electricity Generated (MWh)" },
            { name: "Average Peak Load", description: "AVERAGE of Electricity Demand Peak Load" },
            { name: "Load Factor", description: "Average Load / Peak Load ratio" },
          ],
          examples: [
            "EVALUATE SUMMARIZECOLUMNS('Fact Generation'[Utility], 'Fact Generation'[FY], \"Total MWh\", SUM('Fact Generation'[GEN Electricity Generated (MWh)]), \"Peak MW\", MAX('Fact Generation'[Electricity Demand Peak Load]))",
          ],
        },
        "Fact SAIDI and SAIFI": {
          name: "Fact SAIDI and SAIFI",
          description:
            "Reliability indices: SAIDI (System Average Interruption Duration Index) and SAIFI (System Average Interruption Frequency Index) per utility per fiscal year.",
          columns: [
            { name: "Utility", type: "string", description: "Utility acronym" },
            { name: "FY", type: "string", description: "Fiscal year" },
            { name: "SAIDI Value", type: "number", description: "SAIDI in minutes or hours (check data)" },
            { name: "SAIFI Value", type: "number", description: "SAIFI in interruptions per customer" },
            { name: "Service Area", type: "string", description: "Geographic service area" },
          ],
          measures: [
            { name: "Average SAIDI", description: "AVERAGE of SAIDI Value" },
            { name: "Average SAIFI", description: "AVERAGE of SAIFI Value" },
          ],
          examples: [
            "EVALUATE SUMMARIZECOLUMNS('Fact SAIDI and SAIFI'[Utility], 'Fact SAIDI and SAIFI'[FY], \"SAIDI\", SUM('Fact SAIDI and SAIFI'[SAIDI Value]), \"SAIFI\", SUM('Fact SAIDI and SAIFI'[SAIFI Value])) ORDER BY 'Fact SAIDI and SAIFI'[SAIDI Value] ASC",
          ],
        },
        "Fact Distribution": {
          name: "Fact Distribution",
          description:
            "Distribution network data: line length, transformer capacity, system losses, and customer connections per utility.",
          columns: [
            { name: "Utility", type: "string", description: "Utility acronym" },
            { name: "FY", type: "string", description: "Fiscal year" },
            { name: "Distribution Line Length (km)", type: "number", description: "Total distribution line length in kilometers" },
            { name: "System Losses (%)", type: "number", description: "Technical and non-technical losses as percentage" },
            { name: "Transformer Capacity (MVA)", type: "number", description: "Installed transformer capacity" },
            { name: "Service Area", type: "string", description: "Geographic service area" },
          ],
          measures: [
            { name: "Average System Losses", description: "AVERAGE of System Losses (%)" },
            { name: "Total Line Length", description: "SUM of Distribution Line Length (km)" },
          ],
          examples: [
            "EVALUATE SUMMARIZECOLUMNS('Fact Distribution'[Utility], 'Fact Distribution'[FY], \"Losses %\", AVERAGE('Fact Distribution'[System Losses (%)])) ORDER BY 'Fact Distribution'[System Losses (%)] ASC",
          ],
        },
        "Fact FinancialAccounts": {
          name: "Fact FinancialAccounts",
          description:
            "Financial performance: revenue, operating costs, capital expenditure, tariff recovery rates per utility per fiscal year.",
          columns: [
            { name: "Utility", type: "string", description: "Utility acronym" },
            { name: "FY", type: "string", description: "Fiscal year" },
            { name: "Total Revenue", type: "number", description: "Total revenue (local currency)" },
            { name: "Operating Costs", type: "number", description: "Total operating expenditure" },
            { name: "Capital Expenditure", type: "number", description: "Capital investment" },
            { name: "Tariff Recovery Rate (%)", type: "number", description: "Percentage of costs recovered through tariffs" },
            { name: "Accounts Receivable (Days)", type: "number", description: "Average collection period in days" },
          ],
          measures: [
            { name: "Average Tariff Recovery", description: "AVERAGE of Tariff Recovery Rate (%)" },
            { name: "Total Revenue Sum", description: "SUM of Total Revenue" },
          ],
          examples: [
            "EVALUATE SUMMARIZECOLUMNS('Fact FinancialAccounts'[Utility], 'Fact FinancialAccounts'[FY], \"Revenue\", SUM('Fact FinancialAccounts'[Total Revenue]), \"Cost Recovery %\", AVERAGE('Fact FinancialAccounts'[Tariff Recovery Rate (%)]))",
          ],
        },
        "Fact Transmission": {
          name: "Fact Transmission",
          description:
            "Transmission network: line length by voltage level, substation capacity, interconnection points.",
          columns: [
            { name: "Utility", type: "string", description: "Utility acronym" },
            { name: "FY", type: "string", description: "Fiscal year" },
            { name: "Transmission Line Length (km)", type: "number", description: "Total transmission line length" },
            { name: "Voltage Level", type: "string", description: "Voltage level (e.g., 33kV, 66kV, 132kV)" },
            { name: "Substation Capacity (MVA)", type: "number", description: "Installed substation capacity" },
          ],
          measures: [
            { name: "Total Transmission Length", description: "SUM of Transmission Line Length (km)" },
          ],
          examples: [
            "EVALUATE SUMMARIZECOLUMNS('Fact Transmission'[Utility], 'Fact Transmission'[FY], \"Line km\", SUM('Fact Transmission'[Transmission Line Length (km)]))",
          ],
        },
        "Fact TariffStructure": {
          name: "Fact TariffStructure",
          description:
            "Tariff details: customer categories, tariff rates, connection charges, and tariff methodology.",
          columns: [
            { name: "Utility", type: "string", description: "Utility acronym" },
            { name: "FY", type: "string", description: "Fiscal year" },
            { name: "Customer Category", type: "string", description: "Residential, Commercial, Industrial, etc." },
            { name: "Tariff Rate (per kWh)", type: "number", description: "Tariff rate in local currency per kWh" },
            { name: "Fixed Charge", type: "number", description: "Monthly fixed charge" },
            { name: "Connection Fee", type: "number", description: "New connection fee" },
          ],
          measures: [
            { name: "Average Tariff Rate", description: "AVERAGE of Tariff Rate (per kWh)" },
          ],
          examples: [
            "EVALUATE SUMMARIZECOLUMNS('Fact TariffStructure'[Utility], 'Fact TariffStructure'[Customer Category], \"Rate\", AVERAGE('Fact TariffStructure'[Tariff Rate (per kWh)]))",
          ],
        },
        "Fact Metering": {
          name: "Fact Metering",
          description:
            "Metering data: total customers, metered vs unmetered, prepayment meters, smart meter penetration.",
          columns: [
            { name: "Utility", type: "string", description: "Utility acronym" },
            { name: "FY", type: "string", description: "Fiscal year" },
            { name: "Total Customers", type: "number", description: "Total customer connections" },
            { name: "Metered Customers", type: "number", description: "Customers with functioning meters" },
            { name: "Unmetered Customers", type: "number", description: "Customers without meters (flat-rate)" },
            { name: "Prepayment Meters", type: "number", description: "Prepayment meter count" },
            { name: "Smart Meters", type: "number", description: "Smart/AMI meter count" },
            { name: "Metering Rate (%)", type: "number", description: "Percentage of customers metered" },
          ],
          measures: [
            { name: "Overall Metering Rate", description: "AVERAGE of Metering Rate (%)" },
            { name: "Total Customer Count", description: "SUM of Total Customers" },
          ],
          examples: [
            "EVALUATE SUMMARIZECOLUMNS('Fact Metering'[Utility], 'Fact Metering'[FY], \"Customers\", SUM('Fact Metering'[Total Customers]), \"Metering %\", AVERAGE('Fact Metering'[Metering Rate (%)]))",
          ],
        },
        "Fact Employee": {
          name: "Fact Employee",
          description:
            "Workforce data: total staff, technical vs non-technical, gender breakdown, training metrics.",
          columns: [
            { name: "Utility", type: "string", description: "Utility acronym" },
            { name: "FY", type: "string", description: "Fiscal year" },
            { name: "Total Employees", type: "number", description: "Total headcount" },
            { name: "Technical Staff", type: "number", description: "Technical/engineering staff" },
            { name: "Female Employees", type: "number", description: "Female employees" },
            { name: "Staff Trained", type: "number", description: "Staff receiving training in period" },
          ],
          measures: [
            { name: "Total Workforce", description: "SUM of Total Employees" },
            { name: "Female Participation Rate", description: "Female Employees / Total Employees" },
          ],
          examples: [
            "EVALUATE SUMMARIZECOLUMNS('Fact Employee'[Utility], 'Fact Employee'[FY], \"Staff\", SUM('Fact Employee'[Total Employees]), \"Female %\", DIVIDE(SUM('Fact Employee'[Female Employees]), SUM('Fact Employee'[Total Employees])))",
          ],
        },
        "Fact Safety": {
          name: "Fact Safety",
          description:
            "Safety indicators: lost time injuries, fatalities, safety training completion, incident rates.",
          columns: [
            { name: "Utility", type: "string", description: "Utility acronym" },
            { name: "FY", type: "string", description: "Fiscal year" },
            { name: "Lost Time Injuries", type: "number", description: "Number of LTI incidents" },
            { name: "Fatalities", type: "number", description: "Workplace fatalities" },
            { name: "LTIFR", type: "number", description: "Lost Time Injury Frequency Rate" },
            { name: "Safety Training Hours", type: "number", description: "Total safety training hours" },
          ],
          measures: [
            { name: "Average LTIFR", description: "AVERAGE of LTIFR" },
          ],
          examples: [
            "EVALUATE SUMMARIZECOLUMNS('Fact Safety'[Utility], 'Fact Safety'[FY], \"LTIFR\", AVERAGE('Fact Safety'[LTIFR])) ORDER BY 'Fact Safety'[LTIFR] ASC",
          ],
        },
        "Fact Customer": {
          name: "Fact Customer",
          description:
            "Customer and electrification data: connections, electrification rate, customer satisfaction.",
          columns: [
            { name: "Utility", type: "string", description: "Utility acronym" },
            { name: "FY", type: "string", description: "Fiscal year" },
            { name: "Total Connections", type: "number", description: "Total electricity connections" },
            { name: "New Connections", type: "number", description: "New connections in period" },
            { name: "Electrification Rate (%)", type: "number", description: "Percentage of households electrified" },
            { name: "Customer Satisfaction Score", type: "number", description: "Survey-based satisfaction score" },
            { name: "Complaints Received", type: "number", description: "Customer complaints logged" },
          ],
          measures: [
            { name: "Average Electrification Rate", description: "AVERAGE of Electrification Rate (%)" },
            { name: "Total Connections Sum", description: "SUM of Total Connections" },
          ],
          examples: [
            "EVALUATE SUMMARIZECOLUMNS('Fact Customer'[Utility], 'Fact Customer'[FY], \"Connections\", SUM('Fact Customer'[Total Connections]), \"Electrification %\", AVERAGE('Fact Customer'[Electrification Rate (%)]))",
          ],
        },
        "Fact UtilityContextData": {
          name: "Fact UtilityContextData",
          description:
            "Utility profile data: ownership type, regulatory framework, service territory characteristics, island/isolation status.",
          columns: [
            { name: "Utility", type: "string", description: "Utility acronym" },
            { name: "FY", type: "string", description: "Fiscal year" },
            { name: "Ownership Type", type: "string", description: "Public, Private, PPP, Community" },
            { name: "Regulatory Framework", type: "string", description: "Regulatory body or framework" },
            { name: "Number of Islands Served", type: "number", description: "Islands in service territory" },
            { name: "Service Area Type", type: "string", description: "Urban, Rural, Mixed, Island" },
            { name: "Country", type: "string", description: "Country name" },
            { name: "Region", type: "string", description: "Pacific sub-region" },
          ],
          measures: [],
          examples: [
            "EVALUATE SUMMARIZECOLUMNS('Fact UtilityContextData'[Utility], 'Fact UtilityContextData'[Country], 'Fact UtilityContextData'[Ownership Type])",
          ],
        },
        "Fact CountryContextData": {
          name: "Fact CountryContextData",
          description:
            "Country-level macro indicators: GDP per capita, population, inflation rate, land area, unemployment.",
          columns: [
            { name: "Country", type: "string", description: "Country name" },
            { name: "FY", type: "string", description: "Fiscal year" },
            { name: "GDP per Capita", type: "number", description: "GDP per capita (USD)" },
            { name: "Population", type: "number", description: "Total population" },
            { name: "Inflation Rate (%)", type: "number", description: "Annual inflation rate" },
            { name: "Unemployment Rate (%)", type: "number", description: "Unemployment rate" },
            { name: "Land Area (km²)", type: "number", description: "Total land area" },
          ],
          measures: [],
          examples: [
            "EVALUATE SUMMARIZECOLUMNS('Fact CountryContextData'[Country], 'Fact CountryContextData'[FY], \"GDP/Capita\", AVERAGE('Fact CountryContextData'[GDP per Capita]))",
          ],
        },
      },
    },
  },
};

/**
 * Resolve a table reference — handles both short names and full names.
 * e.g., "GeneratorsData" → "Fact GeneratorsData"
 */
export function resolveTable(tableHint: string): PbiTable | null {
  const dataset = PBI_SCHEMA.datasets["prism-dashboards-prod"];
  if (!dataset) return null;

  // Direct match
  if (dataset.tables[tableHint]) return dataset.tables[tableHint];

  // Case-insensitive match
  const lower = tableHint.toLowerCase();
  for (const [name, table] of Object.entries(dataset.tables)) {
    if (name.toLowerCase() === lower) return table;
  }

  // Partial match (e.g., "GeneratorsData" matches "Fact GeneratorsData")
  for (const [name, table] of Object.entries(dataset.tables)) {
    if (name.toLowerCase().includes(lower)) return table;
  }

  return null;
}

/**
 * Search for tables or columns matching a keyword.
 * Returns matching tables with a relevance summary.
 */
export function searchSchema(keyword: string): Array<{ table: string; matches: string[] }> {
  const dataset = PBI_SCHEMA.datasets["prism-dashboards-prod"];
  if (!dataset) return [];

  const lower = keyword.toLowerCase();
  const results: Array<{ table: string; matches: string[] }> = [];

  for (const [tableName, table] of Object.entries(dataset.tables)) {
    const matches: string[] = [];

    if (tableName.toLowerCase().includes(lower)) {
      matches.push(`table: ${tableName}`);
    }
    if (table.description.toLowerCase().includes(lower)) {
      matches.push("table description");
    }
    for (const col of table.columns) {
      if (col.name.toLowerCase().includes(lower) || (col.description?.toLowerCase().includes(lower) ?? false)) {
        matches.push(`column: ${col.name}`);
      }
    }
    for (const meas of table.measures) {
      if (meas.name.toLowerCase().includes(lower) || (meas.description?.toLowerCase().includes(lower) ?? false)) {
        matches.push(`measure: ${meas.name}`);
      }
    }

    if (matches.length > 0) {
      results.push({ table: tableName, matches: [...new Set(matches)] });
    }
  }

  return results;
}

/**
 * Get a compact AI-friendly summary of the entire schema.
 * Returns a string suitable for inclusion in the AI's context.
 */
export function getSchemaSummary(): string {
  const dataset = PBI_SCHEMA.datasets["prism-dashboards-prod"];
  if (!dataset) return "No schema available.";

  const lines: string[] = [`Dataset: ${dataset.name} (${dataset.description})`, ""];

  for (const [tableName, table] of Object.entries(dataset.tables)) {
    lines.push(`## ${tableName}`);
    lines.push(`  ${table.description}`);
    lines.push(`  Columns (${table.columns.length}):`);
    for (const col of table.columns) {
      lines.push(`    - ${col.name} (${col.type})${col.description ? ` — ${col.description}` : ""}`);
    }
    if (table.measures.length > 0) {
      lines.push(`  Measures (${table.measures.length}):`);
      for (const meas of table.measures) {
        lines.push(`    - ${meas.name}${meas.description ? ` — ${meas.description}` : ""}`);
      }
    }
    if (table.examples && table.examples.length > 0) {
      lines.push("  Example queries:");
      for (const ex of table.examples) {
        lines.push(`    ${ex}`);
      }
    }
    lines.push("");
  }

  return lines.join("\n");
}
