// GENERATED by scripts/build-terminology-config.ts from the sector_terminology table.
// Do not edit by hand. Source of truth = sector_terminology (BMO-maintainable).
// A bundled snapshot keeps the terminology resolver synchronous + client-safe
// (the client cannot read the DB); regenerate + redeploy after a label change.
//
// NOTE: this initial snapshot was seeded from the 3 ratified rows #2 loaded into
// sector_terminology (Grid / Supply Zone / Catchment); re-run the generator against
// the table to reproduce it once the dev DB is reachable.
import type { Sector } from "./sectors";
import type { ConceptKey } from "./concepts";

export const TERMINOLOGY: Partial<
  Record<Sector, Partial<Record<ConceptKey, { label: string; labelPlural?: string }>>>
> = {
  electricity: { service_area: { label: "Grid", labelPlural: "Grids" } },
  water: { service_area: { label: "Supply Zone", labelPlural: "Supply Zones" } },
  sanitation: { service_area: { label: "Catchment", labelPlural: "Catchments" } },
};
