import type { QueryClass } from "./types";
import type { AllowedReadServiceKey } from "./allowed-read-services";

export interface IntentRouteResult {
  queryClass: QueryClass;
  serviceKey: AllowedReadServiceKey;
  requiresReportPeriod: boolean;
}

const QUERY_CLASS_TO_SERVICE: Record<QueryClass, AllowedReadServiceKey> = {
  completeness: "completeness-summary",
  "review-bottlenecks": "review-bottlenecks",
  "stale-missing-kpi": "stale-missing-kpi",
  "pending-queue": "pending-queue",
  "aggregation-run-summary": "aggregated-run-summary",
  "aggregation-run-details": "aggregated-run-details",
  "aggregation-failure-analysis": "aggregated-failure-analysis",
  "generation-renewable-by-utility-year": "renewable-generation-utility-year",
};

export const requiresReportPeriod = (queryClass: QueryClass): boolean => {
  return [
    "completeness",
    "stale-missing-kpi",
    "pending-queue",
    "aggregation-run-summary",
    "aggregation-failure-analysis",
  ].includes(queryClass);
};

export const routeIntent = (queryClass: QueryClass): IntentRouteResult => {
  return {
    queryClass,
    serviceKey: QUERY_CLASS_TO_SERVICE[queryClass],
    requiresReportPeriod: requiresReportPeriod(queryClass),
  };
};

export const inferQueryClassFromPrompt = (
  prompt: string,
): QueryClass | "AMBIGUOUS" => {
  const normalized = prompt.toLowerCase();

  const matches: QueryClass[] = [];

  if (/(complet(e|ion)|coverage)/.test(normalized)) {
    matches.push("completeness");
  }
  if (/(bottleneck|blocked|delay)/.test(normalized)) {
    matches.push("review-bottlenecks");
  }
  if (/(stale|missing\s+kpi|overdue)/.test(normalized)) {
    matches.push("stale-missing-kpi");
  }
  if (/(pending|queue|awaiting)/.test(normalized)) {
    matches.push("pending-queue");
  }
  if (
    /(aggregat|aggregation|worker run|run summary|run status|calculated)/.test(
      normalized,
    )
  ) {
    matches.push("aggregation-run-summary");
  }
  if (
    /(run id|details for run|outcomes for run|show run details)/.test(
      normalized,
    )
  ) {
    matches.push("aggregation-run-details");
  }
  if (
    /(skip reason|failure analysis|why (was|were).*(skipped|failed))/i.test(
      normalized,
    )
  ) {
    matches.push("aggregation-failure-analysis");
  }
  if (
    /(renewable|energy generated|generation by|how much.*generated|generated by .* in 20\d\d)/.test(
      normalized,
    )
  ) {
    matches.push("generation-renewable-by-utility-year");
  }

  if (matches.length !== 1) {
    return "AMBIGUOUS";
  }

  return matches[0];
};
