/**
 * Adds the 15 function-neutral measure subcategories for the condensed measure set
 * (user-provided, 2026-07-09). List 13 = Input Subcategory, parent 205 = Operational.
 * Idempotent (skips names already present in list 13); syncs the id sequence first.
 * MUST also be run against prod (list members are data; deploys don't sync them).
 */
import { sql } from "drizzle-orm";
import { db } from "@/db/connection";

const ROWS: Array<[string, string]> = [
  ["Capacity", "Rated capacity of an equipment"],
  ["Customers", "Customer count or meter count"],
  ["Downtime", "Covers planned and unplanned downtimes events and duration"],
  ["Electricity Consumed", "Electricity consumed by some function or use"],
  ["Electricity Demand", "Electricity demand for as recorded for a grid"],
  ["Electricity Discharged", "Electricity discharged by an Energy Storage System or equipment"],
  ["Electricity Generated", "Electricity generated by a generator"],
  ["Electricity Purchased", "Electricity purchased from non-utility energy providers"],
  ["Electricity Sent", "Electricity sent from usually a transmission network"],
  ["Electricity Stored", "Electricity stored within an Energy Storage System or equipment"],
  ["Fuel and Oil", "Fuel Oil and Lubrication Oil used by generators"],
  ["Network", "Refers to either the Distribution or Transmission network. Content will classify which network."],
  ["Period Hours", "Hours elapsed during reporting period"],
  ["Solar Environment", "Environmental variables that affect the performance of solar panels"],
  ["Transformers", "Refers to any transformer used in the electricity network. Context determines type of transformer."],
];

async function main() {
  await db.execute(sql`
    SELECT setval('managed_list_items_id_seq', (SELECT max(id) FROM managed_list_items))`);

  let inserted = 0;
  let skipped = 0;
  for (const [name, description] of ROWS) {
    const exists = await db.execute(sql`
      SELECT id FROM managed_list_items WHERE list_id = 13 AND name = ${name}`);
    if (((exists.rows ?? exists) as unknown[]).length > 0) {
      skipped++;
      console.log(`${name}: already exists — skip`);
      continue;
    }
    const r = await db.execute(sql`
      INSERT INTO managed_list_items (list_id, parent_id, name, description, is_active, color)
      VALUES (13, 205, ${name}, ${description}, true, '#D5D5D5')
      RETURNING id`);
    const id = ((r.rows ?? r) as { id: number }[])[0]?.id;
    inserted++;
    console.log(`${name}: inserted (id ${id})`);
  }
  console.log(`done — ${inserted} inserted, ${skipped} skipped`);

  const verify = await db.execute(sql`
    SELECT id, name FROM managed_list_items
    WHERE list_id = 13 AND parent_id = 205 ORDER BY name`);
  console.log("list 13 / parent 205 now:", JSON.stringify(verify.rows ?? verify));
  process.exit(0);
}

main().catch((e) => { console.error(e); process.exit(1); });
