/**
 * Generate lib/terminology/terminology.generated.ts from the `sector_terminology`
 * table (stream #13, Phase 5b). The BMO-maintainable table is the source of truth;
 * this bundles a synchronous, client-safe snapshot for the terminology resolver
 * (the client cannot read the DB). Run after any label change, then redeploy:
 *
 *   npx tsx scripts/build-terminology-config.ts
 *
 * git-first: commit the regenerated file. Idempotent — re-running with an unchanged
 * table reproduces the same file.
 */
import "dotenv/config";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { eq } from "drizzle-orm";

import { db } from "@/db/connection";
import { sectors } from "@/db/schema/sector";
import { sectorTerminology } from "@/db/schema/sectorTerminology";

async function main() {
  const rows = await db
    .select({
      code: sectors.code,
      concept: sectorTerminology.concept_key,
      label: sectorTerminology.label,
      labelPlural: sectorTerminology.label_plural,
    })
    .from(sectorTerminology)
    .innerJoin(sectors, eq(sectors.id, sectorTerminology.sector_id))
    .orderBy(sectors.sort_order, sectorTerminology.concept_key);

  const map: Record<string, Record<string, { label: string; labelPlural?: string }>> = {};
  for (const r of rows) {
    (map[r.code] ??= {})[r.concept] = r.labelPlural
      ? { label: r.label, labelPlural: r.labelPlural }
      : { label: r.label };
  }

  const body =
    "// GENERATED by scripts/build-terminology-config.ts from the sector_terminology table.\n" +
    "// Do not edit by hand. Source of truth = sector_terminology (BMO-maintainable).\n" +
    "// A bundled snapshot keeps the terminology resolver synchronous + client-safe\n" +
    "// (the client cannot read the DB); regenerate + redeploy after a label change.\n" +
    '\nimport type { Sector } from "./sectors";\n' +
    'import type { ConceptKey } from "./concepts";\n\n' +
    "export const TERMINOLOGY: Partial<\n" +
    "  Record<Sector, Partial<Record<ConceptKey, { label: string; labelPlural?: string }>>>\n" +
    "> = " +
    JSON.stringify(map, null, 2) +
    ";\n";

  const out = resolve(process.cwd(), "lib/terminology/terminology.generated.ts");
  writeFileSync(out, body, "utf8");
  console.log(`Wrote ${rows.length} terminology rows (${Object.keys(map).length} sectors) → ${out}`);
}

main().then(
  () => process.exit(0),
  (e) => {
    console.error("FAILED:", (e as Error).message);
    process.exit(1);
  },
);
