/**
 * Build lib/countries/reference.generated.ts — the enriched country reference that
 * `ensureCountry` and the currency pre-seed import (stream #13). A bundled TS
 * module (not a runtime CSV read) so it ships reliably in the Next server bundle.
 *
 * Joins the authoritative UNSD M49 geography (db/seed-data/un-m49.csv) with the
 * datasets/country-codes dataset (dial code + ISO-4217 currency), matched on ISO
 * alpha-3.
 *
 * Regenerate:
 *   1. download https://raw.githubusercontent.com/datasets/country-codes/master/data/country-codes.csv
 *   2. npx tsx scripts/build-country-reference.ts <path-to-country-codes.csv>
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

// quote-aware CSV line splitter (datasets/country-codes is comma+quoted)
function splitCsv(line: string): string[] {
  const out: string[] = [];
  let cur = "";
  let q = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (q) {
      if (ch === '"') {
        if (line[i + 1] === '"') { cur += '"'; i++; } else q = false;
      } else cur += ch;
    } else if (ch === ",") { out.push(cur); cur = ""; }
    else if (ch === '"') q = true;
    else cur += ch;
  }
  out.push(cur);
  return out;
}

// dial_code column is varchar(10) — take the primary numeric code, keep it short
function cleanDial(raw: string): string {
  if (!raw) return "";
  const first = raw.split(/[,;]| and /i)[0].trim(); // "1-787 and 1-939" -> "1-787"
  return first.replace(/[^\d+-]/g, "").slice(0, 10);
}

function main() {
  const ccPath = process.argv[2];
  if (!ccPath) throw new Error("usage: tsx build-country-reference.ts <country-codes.csv>");

  // --- datasets/country-codes: iso3 -> { dial, currencyCode, currencyName } ---
  // eslint-disable-next-line security/detect-non-literal-fs-filename -- dev-only generator, path from CLI arg
  const ccText = readFileSync(ccPath, "utf8").replace(/^﻿/, "");
  const ccLines = ccText.split(/\r?\n/).filter((l) => l.trim());
  const ccHead = splitCsv(ccLines[0]);
  const ci = (n: string) => ccHead.findIndex((h) => h.trim() === n);
  const cIso3 = ci("ISO3166-1-Alpha-3");
  const cDial = ci("Dial");
  const cCur = ci("ISO4217-currency_alphabetic_code");
  const cCurName = ci("ISO4217-currency_name");
  const enrich = new Map<string, { dial: string; cur: string; curName: string }>();
  for (const line of ccLines.slice(1)) {
    const c = splitCsv(line);
    const iso3 = (c[cIso3] ?? "").trim().toUpperCase();
    if (!iso3) continue;
    // some territories list multiple currencies (e.g. Haiti "HTG,USD") — take the primary
    const primaryCur = (c[cCur] ?? "").split(",")[0].trim().toUpperCase();
    const primaryCurName = (c[cCurName] ?? "").split(",")[0].trim();
    enrich.set(iso3, {
      dial: cleanDial(c[cDial] ?? ""),
      cur: primaryCur,
      curName: primaryCurName,
    });
  }

  // --- UNSD M49 (authoritative geography) ---
  const m49Text = readFileSync(resolve(process.cwd(), "db/seed-data/un-m49.csv"), "utf8").replace(/^﻿/, "");
  const m49Lines = m49Text.split(/\r?\n/).filter((l) => l.trim());
  const mHead = m49Lines[0].split(";");
  const mi = (n: string) => mHead.findIndex((h) => h.trim() === n);
  const mM49 = mi("M49 Code"), mName = mi("Country or Area"), mIso2 = mi("ISO-alpha2 Code"),
    mIso3 = mi("ISO-alpha3 Code"), mSubC = mi("Sub-region Code"), mSubN = mi("Sub-region Name"),
    mRegN = mi("Region Name");

  const rows: {
    m49: number; name: string; iso2: string; iso3: string; dial: string;
    currencyCode: string; currencyName: string; subRegionCode: number | null;
    subRegionName: string; regionName: string;
  }[] = [];
  let missingCur = 0, missingSub = 0;
  for (const line of m49Lines.slice(1)) {
    const c = line.split(";");
    const iso3 = (c[mIso3] ?? "").trim().toUpperCase();
    const subCode = (c[mSubC] ?? "").trim();
    if (!iso3) continue; // skip region/subregion aggregate rows w/o a country
    const e = enrich.get(iso3) ?? { dial: "", cur: "", curName: "" };
    if (!e.cur) missingCur++;
    if (!subCode) missingSub++;
    rows.push({
      m49: Number(c[mM49].trim()),
      name: (c[mName] ?? "").trim(),
      iso2: (c[mIso2] ?? "").trim(),
      iso3,
      dial: e.dial,
      currencyCode: e.cur,
      currencyName: e.curName,
      subRegionCode: subCode ? Number(subCode) : null,
      subRegionName: (c[mSubN] ?? "").trim(),
      regionName: (c[mRegN] ?? "").trim(),
    });
  }
  rows.sort((a, b) => a.m49 - b.m49);

  const banner =
    "// GENERATED by scripts/build-country-reference.ts — do not edit by hand.\n" +
    "// Source: db/seed-data/un-m49.csv (UNSD M49) + datasets/country-codes (dial + ISO-4217).\n";
  const body =
    banner +
    "\nexport interface CountryRef {\n" +
    "  m49: number;\n  name: string;\n  iso2: string;\n  iso3: string;\n  dial: string;\n" +
    "  currencyCode: string;\n  currencyName: string;\n  subRegionCode: number | null;\n" +
    "  subRegionName: string;\n  regionName: string;\n}\n\n" +
    "export const COUNTRY_REFERENCE: CountryRef[] = " +
    JSON.stringify(rows, null, 2) +
    ";\n\nexport const COUNTRY_REFERENCE_BY_M49: Map<number, CountryRef> = new Map(\n" +
    "  COUNTRY_REFERENCE.map((r) => [r.m49, r]),\n);\n";

  const outPath = resolve(process.cwd(), "lib/countries/reference.generated.ts");
  writeFileSync(outPath, body, "utf8");
  console.log(`Wrote ${rows.length} rows → ${outPath}`);
  console.log(`  rows with no currency: ${missingCur}, no sub-region code: ${missingSub}`);
  const distinctCur = new Set(rows.map((r) => r.currencyCode).filter(Boolean));
  console.log(`  distinct ISO-4217 currencies: ${distinctCur.size}`);
}

main();
