/**
 * Generate lib/chatbot/generated/question-bank.ts from
 * app/prism-ai/chatbot-question-bank.yaml.
 *
 * The YAML file is the source of truth for refusal and follow-up patterns.
 * Run via:  npm run generate-chatbot-prompt
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import YAML from "yaml";

interface YamlRefusal {
  id: string;
  pattern: string;
  when_persona_in?: ReadonlyArray<string>;
  response: string;
}

interface YamlFollowup {
  pattern: string;
  action: string;
  dimension?: string;
  bind?: string;
  direction?: string;
  n?: number;
  guardrails?: ReadonlyArray<string>;
}

interface YamlBank {
  version: number;
  refusals: ReadonlyArray<YamlRefusal>;
  followups: ReadonlyArray<YamlFollowup>;
}

const ROOT = resolve(__dirname, "..");
const SOURCE = resolve(ROOT, "app/prism-ai/chatbot-question-bank.yaml");
const OUTPUT = resolve(ROOT, "lib/chatbot/generated/question-bank.ts");

const ALLOWED_PERSONAS = new Set(["utility", "donor", "regulator", "external"]);

const describeFollowupAction = (followup: YamlFollowup): string => {
  switch (followup.action) {
    case "re_run_with_dimension":
      return `Re-run the previous query grouped by ${followup.dimension ?? "the named dimension"}.`;
    case "re_run_with_period":
      return `Re-run the previous query against the ${followup.bind ?? "previous"} report period.`;
    case "limit": {
      const direction = followup.direction ?? "top";
      const n = followup.n ?? 5;
      return `Apply a ${direction}-N limit (default N=${n}) to the previous result.`;
    }
    case "re_render":
      return `Re-render the previous result using the requested ${followup.bind ?? "format"} via the visualization JSON block.`;
    case "explain_last_result":
      return "Explain the previous result: drivers, contributing inputs, and confidence.";
    case "re_run_with_peer":
      return `Re-run the previous query with the named ${followup.bind ?? "peer"} added.`;
    case "drill_in":
      return `Expand the named ${followup.bind ?? "row"}: inputs, history, comments, related KPIs.`;
    case "export_last_result": {
      const guardrail = followup.guardrails?.length
        ? ` (${followup.guardrails.join("; ")})`
        : "";
      return `Offer export only within the user's authorised scope${guardrail}.`;
    }
    default:
      return followup.action;
  }
};

const tsLiteral = (value: string): string =>
  `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;

const main = () => {
  const yamlText = readFileSync(SOURCE, "utf8");
  const bank = YAML.parse(yamlText) as YamlBank;

  if (!bank || bank.version !== 1) {
    throw new Error(
      `Unexpected question bank version: ${bank?.version ?? "missing"}`,
    );
  }

  if (!Array.isArray(bank.refusals) || bank.refusals.length === 0) {
    throw new Error("YAML refusals block is empty.");
  }

  if (!Array.isArray(bank.followups) || bank.followups.length === 0) {
    throw new Error("YAML followups block is empty.");
  }

  const refusalEntries = bank.refusals.map((refusal) => {
    if (!refusal.id || !refusal.pattern || !refusal.response) {
      throw new Error(
        `Refusal entry missing required fields: ${JSON.stringify(refusal)}`,
      );
    }
    const personas = refusal.when_persona_in?.filter((persona: string) =>
      ALLOWED_PERSONAS.has(persona),
    );
    const personasLine = personas?.length
      ? `\n    appliesTo: [${personas.map(tsLiteral).join(", ")}],`
      : "";
    return `  {
    id: ${tsLiteral(refusal.id)},
    pattern: ${tsLiteral(refusal.pattern)},${personasLine}
    response: ${tsLiteral(refusal.response)},
  }`;
  });

  const followupEntries = bank.followups.map((followup) => {
    if (!followup.pattern || !followup.action) {
      throw new Error(
        `Followup entry missing required fields: ${JSON.stringify(followup)}`,
      );
    }
    return `  {
    pattern: ${tsLiteral(followup.pattern)},
    action: ${tsLiteral(describeFollowupAction(followup))},
  }`;
  });

  const banner = `// AUTO-GENERATED by scripts/generate-chatbot-prompt.ts.
// Do not edit by hand. Source: app/prism-ai/chatbot-question-bank.yaml.
// Re-run \`npm run generate-chatbot-prompt\` after editing the YAML.

export interface GeneratedRefusalPattern {
  id: string;
  pattern: string;
  appliesTo?: ReadonlyArray<"utility" | "donor" | "regulator" | "external">;
  response: string;
}

export interface GeneratedFollowupPattern {
  pattern: string;
  action: string;
}

export const GENERATED_REFUSAL_PATTERNS: ReadonlyArray<GeneratedRefusalPattern> = [
${refusalEntries.join(",\n")},
];

export const GENERATED_FOLLOWUP_PATTERNS: ReadonlyArray<GeneratedFollowupPattern> = [
${followupEntries.join(",\n")},
];
`;

  mkdirSync(dirname(OUTPUT), { recursive: true });
  writeFileSync(OUTPUT, banner, "utf8");
  console.log(
    `Generated ${OUTPUT} (${bank.refusals.length} refusals, ${bank.followups.length} followups).`,
  );
};

main();
