import { describe, expect, it } from "vitest";

import { inferQueryClassFromPrompt, routeIntent } from "@/lib/ai/intent-router";
import { validateQueryClassContext } from "@/lib/ai/query-class-map";

describe("intent router", () => {
  it("routes known query class to expected service", () => {
    const routed = routeIntent("completeness");
    expect(routed.serviceKey).toBe("completeness-summary");
    expect(routed.requiresReportPeriod).toBe(true);
  });

  it("infers query class from clear prompt", () => {
    expect(inferQueryClassFromPrompt("show stale missing KPI records")).toBe(
      "stale-missing-kpi",
    );
  });

  it("returns ambiguous when prompt matches multiple classes", () => {
    expect(
      inferQueryClassFromPrompt("show pending completeness bottlenecks"),
    ).toBe("AMBIGUOUS");
  });

  it("infers renewable generation utility-year prompts", () => {
    expect(
      inferQueryClassFromPrompt(
        "How much renewable energy was generated by Energy Fiji Limited in 2023?",
      ),
    ).toBe("generation-renewable-by-utility-year");
  });

  it("infers aggregation run summary prompts", () => {
    expect(
      inferQueryClassFromPrompt("show aggregation worker run summary"),
    ).toBe("aggregation-run-summary");
  });

  it("allows prompt-first query execution without explicit filter context", () => {
    expect(() => validateQueryClassContext("pending-queue", {})).not.toThrow();
    expect(() =>
      validateQueryClassContext("aggregation-run-details", {}),
    ).not.toThrow();
    expect(() =>
      validateQueryClassContext("generation-renewable-by-utility-year", {}),
    ).not.toThrow();
  });
});
